Separate `schemes` in `apinetlet` into `managerScheme` and `apinetletScheme`
ironcore-dev/ironcore-net pull request #310
Opened 2024-07-29 13:03 UTC by balpert89

Fixes #309

2024-07-29 13:06 UTC, balpert89 commented
@sujeet01 @Rohit-0505 https://github.com/ironcore-dev/ironcore-net/pull/310/files#diff-cd513991cc10b556eb34e9aa31ffbe2e3090219f8ff47f0688ea2e07250a2db3R665-R673 these enqueue funcs produce the following error:
`2024-07-29T12:45:28Z    ERROR   controller-runtime.source.EventHandler  kind must be registered to the Scheme   {"error": "no kind is registered for the type v1alpha1.Network in scheme \"pkg/runtime/scheme.go:100\""}`

The other controllers are running as expected, please have a look and fix.

@afritzler hope the styling is okay, my formatter is a bit more picky :)

2024-07-29 13:21 UTC, afritzler requested changes
Thanks @balpert89 for you PR. Can we please keep the method signature and invocation in a single line as we have this code style everywhere else. Only when the parameters are going over 100 chars we typically put them on individual lines.

2024-07-29 13:21 UTC, afritzler commented on apinetlet/controllers/network_controller.go
> +			peeringPrefixes, err := r.getAPINetNetworkPeeringPrefixes(
Single line please.

2024-07-29 13:21 UTC, afritzler commented on apinetlet/controllers/network_controller.go
> +			handler.EnqueueRequestForSource(r.APINetClient.Scheme(), r.APINetClient.RESTMapper(), &networkingv1alpha1.Network{}),
We have to use the mgr client here.

2024-07-29 20:19 UTC, balpert89 commented
@sujeet01 will continue from here

2024-08-08 08:52 UTC, closed without merging

2024-08-08 08:52 UTC, balpert89 commented
closing this one as agreed we do not need the scheme changes and so on.